// <auto-generated/>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000

namespace Auth0Management.App
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auth0Management.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an action:.
        /// </summary>
        internal static string SelectActionPrompt
        {
            get
            {
                return ResourceManager.GetString("SelectActionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. List users.
        /// </summary>
        internal static string ListUsersOption
        {
            get
            {
                return ResourceManager.GetString("ListUsersOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. Create user.
        /// </summary>
        internal static string CreateUserOption
        {
            get
            {
                return ResourceManager.GetString("CreateUserOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. Update user.
        /// </summary>
        internal static string UpdateUserOption
        {
            get
            {
                return ResourceManager.GetString("UpdateUserOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4. Exit.
        /// </summary>
        internal static string ExitOption
        {
            get
            {
                return ResourceManager.GetString("ExitOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter choice: .
        /// </summary>
        internal static string EnterChoicePrompt
        {
            get
            {
                return ResourceManager.GetString("EnterChoicePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid choice..
        /// </summary>
        internal static string InvalidChoice
        {
            get
            {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
    }
}
